[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Galbot Academy"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Isaac Academy 主线项目：Galbot One Golf 的资产、任务与训练（Isaac Lab 2.3.2）"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["galbot", "isaaclab", "academy"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "galbot_academy"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"